### ISSUE TITLE
Additional mongod.conf properties

### ISSUE THREAD

**Issue by pmackay** [UnderGreen/ansible-role-mongodb#45]
I would like the following properties supported in the `mongod.conf` file. Please suggest if it would be ok to add these or if there is any issue adding them as configuration options.
- `rest`
- `pidfilepath`
- `profile`
- `directoryperdb`

**Comment by ppizarro** [comment]
- net.http (rest): "MongoDB 3.6 removes the deprecated net.http options. The options have been deprecated since version 3.2." I think it is not worth implementing this option once it is deprecated.
- profile: implemented on MR #152 
- directoryperdb: already implemented on master
- pidfilepath: this config we still do not have

**Comment by UnderGreen** [comment]
Added last changes from request in https://github.com/UnderGreen/ansible-role-mongodb/pull/152
