### ISSUE TITLE
mongo2 and mongo3 fail when mongo_* targets are run independently

### ISSUE THREAD

**Issue by cromarty** [UnderGreen/ansible-role-mongodb#98]
Hello Sergei.  I am just learning Ansible and MongoDB and using your great role.  I have a problem with it though. When I run:

ansible-playbook site.yml target=mongo_master

and then:

ansible-playbook site.yml target=mongo_replicas

mongo2 and mongo3 fail in the second invocation.

When I run:

ansible-playbook site.yml target=mongo:children

All is fine.

Something is not persisting between individual runs of targets.

I get the error ansible_default_ipv4 is not in the dictionary in the second target.

**Comment by UnderGreen** [comment]
Hi @cromarty. You can't use this role to play only with `mongo_replicas`. Because to create replicas ansible should know address of mongodb master to connect for. In other words - how ansible will know about master if you run playbook without master?

Because my role is idempotent you feel free to run it for whole cluster every time, there will not changes, if you didn't change something.
